### PR TITLE
Add `LD_LIBRARY_PATH`

### PR DESCRIPTION
**Pull request by armanbilge**

### CODE REVIEW

**Comment by rossabaker** [comment]
What problem are we facing here?  `LIBRARY_PATH` is used at compile time.  I haven't yet needed `LD_LIBRARY_PATH`, which is the runtime setting.

**Comment by armanbilge** [comment]
Huh, what uses `LIBRARY_PATH`? I don't think I've seen that before.

I'm hoping that we can remove some of the custom configuration from the http4s build, if all the envs are properly set.
https://github.com/http4s/http4s/blob/4c644d4c67028519316442cbcb7798c3d0647f3d/build.sbt#L887

**Comment by rossabaker** [comment]
`LIBRARY_PATH` is used at link time.  That was the only thing I needed to get the tests passing here, and I'm a little surprised they're passing now.

Does the http4s build not work without that variable?

**Comment by armanbilge** [comment]
Ah, my bad. `LIBRARY_PATH` is indeed a thing. Sorry.

https://stackoverflow.com/a/42997381

So I think the change I want to make is additive.

**Comment by armanbilge** [comment]
Ok very sorry for wasting your time ... it seems that everything works perfectly without all the extra configuration I was doing. Thanks for setting me straight 😅 
- https://github.com/http4s/http4s/pull/6784

**Pull request closed without merging**
