### PR TITLE
Use `zlib.dev` to get headers

### PR DESCRIPTION
**Pull request by armanbilge**
So that `zlib.h` is added to `$DEVSHELL_DIR/include/`

### CODE REVIEW

**Review by rossabaker — APPROVED** [review]

**Comment by rossabaker** [comment]
If you'd rather be more a la carte with the locations, you can also add an environment variable similar to how LLVM_BIN is defined:

```nix
          {
            name = "ZLIB_DIR";
            value = "${pkgs.zlib.dev}";
          }
```

**Comment by armanbilge** [comment]
Thanks, good to know. I guess since this is a core Scala Native dependency it's fine to bake it in.

A la carte may be a good fit for s2n-tls, which is a more Typelevel-specific dependency.

I realized that without `zlib.out` we are missing the actual library ...

**Comment by rossabaker** [comment]
I'm confused why this was necessary.  Maybe it's different on Linux?  I don't have that machine handy.

```console
$ nix develop nixpkgs#zlib
bash-5.1$ head -n 3 $DEVSHELL_DIR/include/zlib.h
/* zlib.h -- interface of the 'zlib' general purpose compression library
  version 1.2.12, March 11th, 2022
```

**Comment by armanbilge** [comment]
/shrug

```
$ nix develop nixpkgs#zlib
$ head -n 3 $DEVSHELL_DIR/include/zlib.h
head: cannot open '/include/zlib.h' for reading: No such file or directory
```

**Comment by rossabaker** [comment]
I think we can do better with pkg-config.  I'm experimenting.

**Comment by rossabaker** [comment]
Fixed in #63.

**Pull request closed without merging**
